### PR TITLE
Fix/proposal modal

### LINKED ISSUE #94: Frontend: Turn Create proposal form into a component
https://github.com/Peerprotocol/peer-on-strk/blob/89f529cdd29535aeaf0973e986ddb88ee3186256/frontend/src/app/app/LendMarket/lendersMarket.tsx

There is a form here which is common between the lenders market and the borrow market, the form is used to create lending and borrow proposals on the app.
the task is to 

- [ ] turn it into a component that can be shared by both files
- [ ] the input fields for the token and collateral should be a dropdown instead of an input
- [ ] Interest rate and duration  should also be a dropdown instead of a range
- [ ]  duration should start from 7 days
- [ ]  make sure all associated functions work as they are supposed to .

Required Skill: Cairo , Frontend
ETA: 2 days

### PR DESCRIPTION
**Pull request by Franklivania**
closes #94 

**In this PR, I...**

- Built a reusable dropdown with multiselect ability
- Built a reusable modal for versatility
- created a new proposal modal to handle all `Create Proposal` functionality in `proposalModal`
- built a reusable `handleClickOutside` hook to handle ref clicks outside a component and integrated it in the modal
- created new folders in component `custom`, which houses the `dropdown`, `layout`, which houses the modal
- converted `token`, `collateral`, `duration` and `interestRate` to dropdown select functionality
- made the duration starts from 7 days

### CODE REVIEW

File: frontend/src/components/proposalModal/_data.tsx [hunk 1]
```diff
@@ -0,0 +1,33 @@
+import Image from "next/image";
+
+
+let size = 24;
+export const tokenOptions = [
+  { label: <span className='flex items-center gap-2'><Image src="/icons/strk.svg" alt='Starknet' width={size} height={size} /> STARKNET</span>, value: "starknet" },
```
Comment (Dprof-in-tech) [inline frontend/src/components/proposalModal/_data.tsx:6]: token options should be Strk and ETH tokens

And their values should be the contract addresses of these tokens.

File: frontend/src/components/proposalModal/_data.tsx [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  { label: <span className='flex items-center gap-2'><Image src="/icons/solanaLogoMark.svg" alt='Solana' width={size} height={size} /> Solana</span>, value: "solana" },
+  { label: <span className='flex items-center gap-2'><Image src="/icons/xionLogo.png" alt='xion' width={size} height={size} /> XION</span>, value: "xion" },
+];
+
+// Interest rate options from 15% to 70%
```
Comment (Dprof-in-tech) [inline frontend/src/components/proposalModal/_data.tsx:11]: interest rates should start at 1% and be capped at 10%

File: frontend/src/components/proposalModal/_data.tsx [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+  { label: '14 days', value: '14' },
+  { label: '21 days', value: '21' },
+  { label: '28 days', value: '28' },
+  { label: '35 days', value: '35' },
+  { label: '42 days', value: '42' },
+];
+
+
+
+export const collateralOptions = [
```
Comment (Dprof-in-tech) [inline frontend/src/components/proposalModal/_data.tsx:29]: the collateral options should also be Strk and eth tokens and thier value when selected should be the contract addresses of this token

File: frontend/src/components/proposalModal/index.tsx [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+    collateral: '',
+    quantity: '',
+    duration: '',
+    interestRate: '',
+  });
+
+  const collateralAmount = Math.floor(Number(formData.quantity || 0) * 1.3);
+
+  const { writeAsync: createProposal, isLoading } = useContractWrite({
+    calls: [
```
Comment (Dprof-in-tech) [inline frontend/src/components/proposalModal/index.tsx:45]: Screenshot 2025-01-24 at 07 25 19


this is the current result of your implementation, its not working

File: frontend/src/components/layout/modal/index.tsx [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+  title?: string | string[];
+  show: boolean,
+  onClose: () => void;
+  children: ReactNode,
+};
+
+export default function Modal({ title, children, show, onClose }: ModalProps) {
+  const ref = useClickOutside(onClose, show);
+  return (
+    <div className={`fixed top-0 left-0 w-full h-screen overflow-hidden bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center ${show ? "scale-1" : "scale-0"}`}>
```
Comment (Dprof-in-tech) [inline frontend/src/components/layout/modal/index.tsx:16]: the background color should be the original white that has been there. do not make it black

**Review by Dprof-in-tech — CHANGES_REQUESTED** [review]

File: frontend/src/components/proposalModal/_data.tsx (hunk 2 above)
Comment (Dprof-in-tech) [reply frontend/src/components/proposalModal/_data.tsx:11]: literal 1 - 10

**Comment by Dprof-in-tech** [comment]
Screenshot 2025-01-24 at 15 19 35


also in the data file, find that part in the image and change it to match what is in the image

**Review by Dprof-in-tech — APPROVED** [review]
all done. Thank you for your contribution.
